name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7

    - name: Set up Go
      uses: actions/setup-go@v7
      with:
        go-version-file: go.mod
        cache: true

    - name: Test
      run: go test -race ./...

    - name: Vet
      run: go vet ./...

    - name: Build
      run: go build ./...
